config/routes.rb
Rails.application.routes.draw do
  devise_for :employees

  root to: 'home#index'
  post 'baidu/ocr_idcard', to: 'baidu#ocr_idcard'

  resources :projects, only: [:index, :show, :new, :create] do
    collection do
      get :basic_info
      get :worker
      get :material
      get :claiming
      get :report
    end
  end
  resources :workers, except: [:show, :destroy]
  resources :worker_hours, except: [:show]
  resources :worker_advances, except: [:show]
  resources :worker_settles, only: [:index, :show, :new, :create] do
    collection do
      get :to_be_settled
    end
  end
  resources :vendors, except: [:show, :destroy]
  resources :materials

end

app/models/worker_hour.rb
class WorkerHour < ApplicationRecord

  belongs_to :project, optional: true
  belongs_to :worker, optional: true

  enum work_type: {
    gong: 0,
    area: 1
  }

  enum status: {
    unpaid: 0,
    paid: 1
  }

end

app/controllers/worker_hours_controller.rb
class WorkerHoursController < BaseController

  def index
    @search_params = SearchParams.new(params[:search_params] || {status: :unpaid})
    @worker_hours = WorkerHour.includes(:worker, :project).default_where(@search_params.attributes(self)).order(work_on: :desc).page(params[:page])
  end

  def new
    @worker_hour = WorkerHour.new(quantity: 1)
  end

  def create
    WorkerHour.create(worker_hour_params)
    redirect_to action: :index
  end

  def edit
    @worker_hour = WorkerHour.find params[:id]
  end

  def update
    @worker_hour = WorkerHour.find params[:id]
    @worker_hour.update(worker_hour_params) if @worker_hour.unpaid?
    redirect_to action: :index
  end

  def destroy
    @worker_hour = WorkerHour.find params[:id]
    @worker_hour.destroy if @worker_hour.unpaid?
  end

  private

  def worker_hour_params
    params.require(:worker_hour).permit(:worker_id, :project_id, :work_on, :work_type, :quantity, :amount)
  end

end

app/views/worker_hours/_list.html.erb
<tr id="worker_hour_<%= worker_hour.id %>">
  <td class="center aligned"><%= worker_hour.id %></td>
  <td class="center aligned"><%= worker_hour.worker.name %></td>
  <td class="center aligned"><%= worker_hour.project.name %></td>
  <td class="center aligned"><%= worker_hour.work_on %></td>
  <td class="center aligned"><%= worker_hour.work_type_i18n %></td>
  <td class="center aligned"><%= worker_hour.quantity %><%= worker_hour.gong? ? "工时" : "面积" %></td>
  <td class="center aligned"><%= number_to_currency worker_hour.amount, unit: "¥" %></td>
  <td class="center aligned"><%=  worker_hour.status_i18n %></td>
  <td class="center aligned">
    <% if worker_hour.unpaid? %>
      <%= link_to "修改", edit_worker_hour_path(worker_hour), class: "ui red button"  %>
      <%= link_to "删除", worker_hour_path(worker_hour), remote: true, method: :delete, data: {confirm: "确认删除吗？"}, class: "ui button"  %>
    <% end %>
  </td>
</tr>

app/views/worker_hours/destroy.js.erb
$("#worker_hour_<%= params[:id] %>").remove();

app/views/worker_hours/edit.html.erb
<h3 class="ui red header">工时修改</h3>
<div class="ui red segment">
  <%= simple_form_for @worker_hour, url: worker_hour_path(@worker_hour) do |f| %>
    <div class="four fields">
      <%= f.input :worker_id, as: :select, label: '工人', collection: Worker.form_options, include_blank: "选择工人", input_html: { class: 'ui fluid dropdown' } %>
      <%= f.input :project_id, as: :select, label: '项目', collection: Project.form_options, include_blank: "选择项目", input_html: { class: 'ui fluid dropdown' } %>
    </div>
    <div class="four fields">
      <%= f.input :work_on, as: :string, label: '工作日期', input_html: {onfocus: "(this.type='date')", onblur: "(this.type='text')"} %>
      <%= f.input :work_type, as: :select, label: '结算类型', collection: WorkerHour.work_types_i18n.invert, include_blank: "选择结算类型", input_html: { class: 'ui fluid dropdown' } %>
    </div>
    <div class="four fields">
      <%= f.input :quantity, label: "工时/面积", input_html: {onchange: "calculate_amount();"} %>
      <div class="field">
        <label>单价</label>
        <input type="number" step="any" id="single_price" onchange="calculate_amount();" value="<%= @worker_hour.amount / @worker_hour.quantity %>">
      </div>
      <%= f.input :amount, label: "工资", input_html: {readonly: ""}, wrapper_html: {class: "disabled"} %>
    </div>
    <%= f.submit "提交", class: "ui red button" %>
  <% end %>
</div>
<script>
  function calculate_amount(){
    var quantity = parseFloat($("#worker_hour_quantity").val());
    var single_price = parseFloat($("#single_price").val());
    if(isNaN(quantity)){
      quantity = 0
    }
    if(isNaN(single_price)){
      single_price = 0
    }
    var amount = (quantity * single_price).toFixed(2);
    if(amount > 0){
      $("#worker_hour_amount").val(amount);
    }else{
      $("#worker_hour_amount").val("");
    }
  }
</script>

app/views/worker_hours/index.html.erb
<h3 class="ui red header">工时列表</h3>
<div class="ui red segment">
  <%= simple_form_for @search_params, url: '', method: :get, wrapper: 'semantic_search' do |f| %>
    <div class="ui six column grid">
      <%= f.input :worker_id, as: :select, collection: Worker.form_options, include_blank: "选择工人", input_html: { class: 'ui fluid dropdown' } %>
      <%= f.input :project_id, as: :select, collection: Project.form_options, include_blank: "选择项目", input_html: { class: 'ui fluid dropdown' } %>
      <%= f.input :work_type, as: :select, collection: WorkerHour.work_types_i18n.invert, include_blank: "选择结算类型", input_html: { class: 'ui fluid dropdown' } %>
      <%= f.input :status, as: :select, collection: WorkerHour.statuses_i18n.invert, include_blank: "选择状态", input_html: { class: 'ui fluid dropdown' } %>
      <div class="column">
        <div class="ui left icon input fluid">
          <i class="calendar icon"></i>
          <%= f.input_field "work_on-gte", placeholder: '工作日期-起', onfocus: "(this.type='date')", onblur: "(this.type='text')" %>
        </div>
      </div>
      <div class="column">
        <div class="ui left icon input fluid">
          <i class="calendar icon"></i>
          <%= f.input_field "work_on-lte", placeholder: '工作日期-始', onfocus: "(this.type='date')", onblur: "(this.type='text')" %>
        </div>
      </div>
      <div class="column">
        <%= f.submit '搜索', class: 'ui red button' %>
      </div>
    </div>
  <% end %>
</div>
<div class="ui segment">
  <%= link_to "工时登记", new_worker_hour_path, class: "ui red button" %>
  <table class="ui selectable striped celled table">
    <thead>
      <tr>
        <th class="center aligned">序号</th>
        <th class="center aligned">工人</th>
        <th class="center aligned">项目</th>
        <th class="center aligned">工作日期</th>
        <th class="center aligned">结算类型</th>
        <th class="center aligned">工时/面积</th>
        <th class="center aligned">工资</th>
        <th class="center aligned">状态</th>
        <th class="center aligned">操作</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'list', collection: @worker_hours, as: :worker_hour %>
    </tbody>
  </table>
  <%= paginate @worker_hours %>
</div>

app/views/worker_hours/new.html.erb
<h3 class="ui red header">工时登记</h3>
<div class="ui red segment">
  <%= simple_form_for @worker_hour, url: worker_hours_path do |f| %>
    <div class="four fields">
      <%= f.input :worker_id, as: :select, label: '工人', collection: Worker.form_options, include_blank: "选择工人", input_html: { class: 'ui fluid dropdown' } %>
      <%= f.input :project_id, as: :select, label: '项目', collection: Project.form_options, include_blank: "选择项目", input_html: { class: 'ui fluid dropdown' } %>
    </div>
    <div class="four fields">
      <%= f.input :work_on, as: :string, label: '工作日期', input_html: {onfocus: "(this.type='date')", onblur: "(this.type='text')"} %>
      <%= f.input :work_type, as: :select, label: '结算类型', collection: WorkerHour.work_types_i18n.invert, include_blank: "选择结算类型", input_html: { class: 'ui fluid dropdown' } %>
    </div>
    <div class="four fields">
      <%= f.input :quantity, label: "工时/面积", input_html: {onchange: "calculate_amount();"} %>
      <div class="field">
        <label>单价</label>
        <input type="number" step="any" id="single_price" onchange="calculate_amount();">
      </div>
      <%= f.input :amount, label: "工资", input_html: {readonly: ""}, wrapper_html: {class: "disabled"} %>
    </div>
    <%= f.submit "提交", class: "ui red button" %>
  <% end %>
</div>
<script>
  function calculate_amount(){
    var quantity = parseFloat($("#worker_hour_quantity").val());
    var single_price = parseFloat($("#single_price").val());
    if(isNaN(quantity)){
      quantity = 0
    }
    if(isNaN(single_price)){
      single_price = 0
    }
    var amount = (quantity * single_price).toFixed(2);
    if(amount > 0){
      $("#worker_hour_amount").val(amount);
    }else{
      $("#worker_hour_amount").val("");
    }
  }
</script>