config/routes.rb
Rails.application.routes.draw do
  devise_for :employees

  root to: 'home#index'
  post 'baidu/ocr_idcard', to: 'baidu#ocr_idcard'

  resources :projects, only: [:index, :show, :new, :create] do
    collection do
      get :basic_info
      get :worker
      get :material
      get :claiming
      get :report
    end
  end
  resources :workers, except: [:show, :destroy]
  resources :worker_hours, except: [:show]
  resources :worker_advances, except: [:show]
  resources :worker_settles, only: [:index, :show, :new, :create] do
    collection do
      get :to_be_settled
    end
  end
  resources :vendors, except: [:show, :destroy]
  resources :materials

end

app/models/vendor.rb
class Vendor < ApplicationRecord

  def self.form_options
    Vendor.all.map{|p| [p.name, p.id]}
  end

end

app/controllers/vendors_controller.rb
class VendorsController < BaseController

  def index
    @search_params = SearchParams.new(params[:search_params])
    @vendors = Vendor.default_where(@search_params.attributes(self)).order(id: :desc).page(params[:page])
  end

  def new
    @vendor = Vendor.new
  end

  def create
    Vendor.create(vendor_params)
    redirect_to action: :index
  end

  def edit
    @vendor = Vendor.find params[:id]
  end

  def update
    @vendor = Vendor.find params[:id]
    @vendor.update(vendor_params)
    redirect_to action: :index
  end

  private

  def vendor_params
    params.require(:vendor).permit(:name, :address, :contact, :mobile, :tax_no, :bank, :bank_account_no, :tel, :fax)
  end

end

app/views/vendors/_list.html.erb
<tr>
  <td class="center aligned"><%= vendor.id %></td>
  <td class="center aligned"><%= vendor.name %></td>
  <td class="center aligned"><%= vendor.contact %></td>
  <td class="center aligned"><%= vendor.mobile %></td>
  <td class="center aligned"><%= vendor.tax_no %></td>
  <td class="center aligned"><%= vendor.bank %>[<%= vendor.bank_account_no %>]</td>
  <td class="center aligned"><%= vendor.address %></td>
  <td class="center aligned">
    <%= link_to "修改", edit_vendor_path(vendor), class: "ui red button"  %>
  </td>
</tr>

app/views/vendors/edit.html.erb
<h3 class="ui red header">供应商修改</h3>
<div class="ui red segment">
  <%= simple_form_for @vendor, url: vendor_path(@vendor) do |f| %>
    <div class="four fields">
      <%= f.input :name, label: '供应商名称' %>
    </div>
    <div class="two fields">
      <%= f.input :address, label: '地址' %>
    </div>
    <div class="four fields">
      <%= f.input :contact, label: '联系人' %>
      <%= f.input :mobile, label: '联系人手机号' %>
    </div>
    <div class="four fields">
      <%= f.input :tax_no, label: '税号' %>
      <%= f.input :bank, label: '开户行' %>
      <%= f.input :bank_account_no, label: '开户行账号' %>
    </div>
    <div class="four fields">
      <%= f.input :tel, label: '电话' %>
      <%= f.input :fax, label: '传真' %>
    </div>
    <%= f.submit "提交", class: "ui red button" %>
  <% end %>
</div>

app/views/vendors/index.html.erb
<h3 class="ui red header">供应商列表</h3>
<div class="ui red segment">
  <%= simple_form_for @search_params, url: '', method: :get, wrapper: 'semantic_search' do |f| %>
    <div class="ui five column grid">
      <%= f.input "name-like", placeholder: '供应商名称' %>
      <div class="column">
        <%= f.submit '搜索', class: 'ui red button' %>
      </div>
    </div>
  <% end %>
</div>
<div class="ui segment">
  <%= link_to "供应商登记", new_vendor_path, class: "ui red button" %>
  <table class="ui selectable striped celled table">
    <thead>
      <tr>
        <th class="center aligned">序号</th>
        <th class="center aligned">供应商名称</th>
        <th class="center aligned">联系人</th>
        <th class="center aligned">联系人手机</th>
        <th class="center aligned">税号</th>
        <th class="center aligned">开户行</th>
        <th class="center aligned">地址</th>
        <th class="center aligned">操作</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'list', collection: @vendors, as: :vendor %>
    </tbody>
  </table>
  <%= paginate @vendors %>
</div>

app/views/vendors/new.html.erb
<h3 class="ui red header">供应商登记</h3>
<div class="ui red segment">
  <%= simple_form_for @vendor, url: vendors_path do |f| %>
    <div class="four fields">
      <%= f.input :name, label: '供应商名称' %>
    </div>
    <div class="two fields">
      <%= f.input :address, label: '地址' %>
    </div>
    <div class="four fields">
      <%= f.input :contact, label: '联系人' %>
      <%= f.input :mobile, label: '联系人手机号' %>
    </div>
    <div class="four fields">
      <%= f.input :tax_no, label: '税号' %>
      <%= f.input :bank, label: '开户行' %>
      <%= f.input :bank_account_no, label: '开户行账号' %>
    </div>
    <div class="four fields">
      <%= f.input :tel, label: '电话' %>
      <%= f.input :fax, label: '传真' %>
    </div>
    <%= f.submit "提交", class: "ui red button" %>
  <% end %>
</div>