config/routes.rb
Rails.application.routes.draw do
  devise_for :employees

  root to: 'home#index'
  post 'baidu/ocr_idcard', to: 'baidu#ocr_idcard'

  resources :projects, only: [:index, :show, :new, :create] do
    collection do
      get :basic_info
      get :worker
      get :material
      get :claiming
      get :report
    end
  end
  resources :workers, except: [:show, :destroy]
  resources :worker_hours, except: [:show]
  resources :worker_advances, except: [:show]
  resources :worker_settles, only: [:index, :show, :new, :create] do
    collection do
      get :to_be_settled
    end
  end
  resources :vendors, except: [:show, :destroy]
  resources :materials

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>登录</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
      <%= yield %>
  </body>
</html>

app/views/layouts/employee.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cofo管理系统</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <div class="ui top fixed inverted red large menu">
      <div class="item">Cofo管理系统</div>
      <div class="right menu">
        <%= link_to "退出", destroy_employee_session_path, method: :delete, class: "item" %>
      </div>
    </div>
    <div class="ui left vertical inverted menu fixed" style="height:100vh;margin-top:43px;">
      <div class="item">
        <div class="header"><i class="folder icon"></i>项目管理</div>
        <div class="menu">
          <%= link_to "项目登记", new_project_path, class: "#{params[:controller] == 'projects' && params[:action] == 'new' ? 'active' : ''} item" %>
          <%= link_to "项目列表", projects_path, class: "#{params[:controller] == 'projects' && params[:action] != 'new' ? 'active' : ''} item" %>
        </div>
      </div>
      <div class="item">
        <div class="header"><i class="address card icon"></i>工人管理</div>
        <div class="menu">
          <%= link_to "工人管理", workers_path, class: "#{params[:controller] == 'workers' ? 'active' : ''} item" %>
          <%= link_to "工时管理", worker_hours_path, class: "#{params[:controller] == 'worker_hours' ? 'active' : ''} item" %>
          <%= link_to "借支管理", worker_advances_path, class: "#{params[:controller] == 'worker_advances' ? 'active' : ''} item" %>
          <%= link_to "未结算列表", to_be_settled_worker_settles_path, class: "#{params[:controller] == 'worker_settles' && ['to_be_settled','new'].include?(params[:action]) ? 'active' : ''} item" %>
          <%= link_to "已结算列表", worker_settles_path, class: "#{params[:controller] == 'worker_settles' && !['to_be_settled','new'].include?(params[:action]) ? 'active' : ''} item" %>
        </div>
      </div>
      <div class="item">
        <div class="header"><i class="dolly flatbed icon"></i>材料管理</div>
        <div class="menu">
          <%= link_to "供应商管理", vendors_path, class: "#{params[:controller] == 'vendors' ? 'active' : ''} item" %>
          <%= link_to "材料管理", materials_path, class: "#{params[:controller] == 'materials' ? 'active' : ''} item" %>
        </div>
      </div>
    </div>
    <div class="ui grid" style="margin-top:3px;margin-left:210px;margin-right:5px;">
      <div class="sisteen wide column">
        <%= yield %>
      </div>
    </div>
    <%= yield :scripts %>
  </body>
</html>